# Path to your oh-my-zsh installation.
export ZSH="/Users/cody.spriggs/.oh-my-zsh"

# Set name of the theme to load.
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="robbyrussell"
# ZSH_THEME="afowler"

# Uncomment the following line to automatically update without prompting.
DISABLE_UPDATE_PROMPT="true"

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git bundler brew git-open zsh-z zsh-autosuggestions zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# User configuration

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi
export EDITOR='code'
export RAILS_ENV='development'

# Aliases

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# ZSH Aliases
alias zshrc='code ~/.zshrc'
alias ohmyzsh="code ~/.oh-my-zsh"

# Ruby Aliases
alias be="bundle exec"
alias tests="RAILS_ENV=test bundle exec rspec"
alias fastest="RAILS_ENV=test bundle exec rspec --tag '~skip_on_ci'"
alias bspec="SIMPLECOV=1 RAILS_ENV=test bundle exec rspec"
alias booya="bundle && yarn"

# Git Aliases
alias gap="git add -p"
alias gm--ff="git merge --ff-only"
alias gcmsg="git commit -m"
alias ggpull="git pull --ff-only"
alias ggpush='git push origin $(git_current_branch)'
alias git-touch='git commit --amend --no-edit'
alias git-nuke="git branch | grep -v 'master' | xargs git branch -D"

# CLI Tool Aliases
alias myip="ifconfig en0 | grep 'inet ' | cut -f2 -d ' '"
# alias rm="trash"
# replacement for file-listing command line util `ls`
# https://github.com/ogham/exa
# -T recurse into dirs as a tree
# -L filter levels deep
# -l display extended details and attrs
# -m modified timestamp
# -a show hidden and dot files
# --header row to column
# --icons display icons
alias lga="exa -T -L=2 --git-ignore -l -m -a --header --icons"
alias lta="exa -T -L=2 -l -m -a --header --icons"

# OS Path
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
export PATH="/usr/local/sbin:$PATH"

# MySQL
export PATH="/usr/local/opt/mysql@5.7/bin:$PATH"
# Global Yarn
export PATH="/Users/cody.spriggs/.config/yarn/global/node_modules/.bin:$PATH"

# OpenSSL - commented these out bc they weren't the solution but might be needed?
# export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"
# export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
# export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"
# export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"
export LIBRARY_PATH="$LIBRARY_PATH:/usr/local/opt/openssl@1.1/lib/"

# Zsh-Syntax-Highlighting Plugin
# source /Users/cody.spriggs/Repos/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# ASDF Configuration
. $HOME/.asdf/asdf.sh
export HOMEBGREW_GITHUB_API_TOKEN=171005410
export HOMEBREW_GITHUB_API_TOKEN=e9e5d2785028daf88ee0599c86303d7813e7d4c1

export ARTIFACTORY_USERNAME=cody.spriggs@daveramsey.com
export ARTIFACTORY_TOKEN=AKCp8ihewuhwdfsLCZcw1sXH3jjKrLW4hvq5Kh4VSoZUeknBfNUy1xpGG6PS2Nq12DyjgcX94
export BUNDLE_RAMSEYSOLUTIONS__JFROG__IO=cody.spriggs%40daveramsey.com:AKCp8ihewuhwdfsLCZcw1sXH3jjKrLW4hvq5Kh4VSoZUeknBfNUy1xpGG6PS2Nq12DyjgcX94

# Autogenerated by Front End Artifactory CLI #
if [ -f ~/.rs-artifactory ]; then
  source ~/.rs-artifactory
fi
# END Autogeneration #

### MANAGED BY RANCHER DESKTOP START (DO NOT EDIT)
export PATH="/Users/cody.spriggs/.rd/bin:$PATH"
### MANAGED BY RANCHER DESKTOP END (DO NOT EDIT)
export PATH="/Applications/RubyMine.app/Contents/MacOS:$PATH"
alias rubymine="open -a RubyMine"
